spring:
  application:
    name: batch
  datasource:
    url: jdbc:mysql://localhost:3306/train_batch?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xiaoqian666
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:18080
      datasource:
        degrade:
          nacos:
            server-addr: localhost:8848
            namespace: 8558e8aa-362e-4532-b220-50aa63b98e3b
            data-id: sentinel-batch-degrade
            group-id: SENTINEL_GROUP
            rule-type: degrade
    # sentinel监控feign后，启动会报注入失败，需改成懒加载
    openfeign:
      lazy-attributes-resolution: true
server:
  port: 8003
  servlet:
    context-path: /batch # 路由前缀，方便后期网关管理路由
logging:
  level:
    com.xiaoqian: debug
# sentinel默认不监控feign，需改成true
feign:
  sentinel:
    enabled: true