server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors: # 跨域问题
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]': # 拦截所有请求
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:9000"
              - "http://localhost:9001"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 3600 # 这次跨域检测的有效期

      routes:
        # 当请求是以member为前缀时就会转发到8001端口
        - id: member
          uri: http://localhost:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://localhost:8002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://localhost:8003
          predicates:
            - Path=/batch/**