spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xiaoqian666
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8002
  servlet:
    context-path: /business # 路由前缀，方便后期网关管理路由
logging:
  level:
    com.xiaoqian: debug
seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 8558e8aa-362e-4532-b220-50aa63b98e3b
      group: SEATA_GROUP
      username: nacos
      password: nacos
      context-path:
      data-id: seataServer.properties
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 8558e8aa-362e-4532-b220-50aa63b98e3b
      cluster: default
      username: nacos
      password: nacos
      context-path:
  tx-service-group: train-group # 事务组名称
