spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xiaoqian666
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001
  servlet:
    context-path: /member # 路由前缀，方便后期网关管理路由