spring:
  application:
    name: member
  profiles:
    active: dev
logging:
  level:
    com.xiaoqian: debug
seata:
  tx-service-group: train-group # 事务组名称
  service:
    vgroup-mapping:
      train-group: default # 事务组和seata集群做关联
    grouplist:
      default: localhost:8091 # seata集群对应的机器